[package]
name = "email"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
async-trait = "0.1.83"
jmap-client = "0.3.2"
lazy_static = "1.5.0"
tera = "1.20.0"
tokio = { version = "1.41.0", features = ["full"] }
