name: Test Glass-Slippers

on:
  push:

jobs:
  test-glass-slippers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        fetch-depth: 0
         
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      
      - name: Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Test
        run: |
        ls -al
        ls -al test_data 
        cargo test -- --nocapture
      


